server:
  port: 8088  # Puerto del gateway

spring:
  application:
    name: bookstore-gateway

  main:
    web-application-type: reactive   # ðŸ‘ˆ Necesario para Gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # ðŸ‘‡ Tus rutas
      routes:
        - id: catalog-service
          uri: http://localhost:8080
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: http://localhost:8081
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**