server:
  port: 8088  # Puerto del gateway

spring:
  application:
    name: bookstore-gateway

  main:
    web-application-type: reactive   # ðŸ‘ˆ Necesario para Gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # ðŸ‘‡ Tus rutas
      routes:
        - id: catalog-service
          uri: http://catalog-service:8080
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<segment>.*), /${segment}

        - id: cart-service
          uri: http://cart-service:8081
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<segment>.*), /${segment}

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}
        
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}